name: menu_negacao
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  flutter_lints: ^6.0.0
  flutter_speed_dial: ^7.0.0

flutter:
  uses-material-design: true
